In [18]:
import pandas as pd

In [19]:
df_2019 = pd.read_csv('./신한카드 데이터/df_2019.csv')

In [20]:
df_2019

,거주지,가맹점,가맹점2,업종1,업종2,성별,연령대,이용년월,요일,이용시간대,취급액,이용건수
0,인천,세종,.,여행,숙박,M,20,201901,WHITE,활동,2012000.0,45
1,제주,세종,.,여행,숙박,M,30,201901,WHITE,휴식,1006000.0,30
2,인천,세종,.,여행,숙박,F,50,201901,WHITE,활동,2665900.0,45
3,대전,세종,.,여행,체험,M,50,201901,WHITE,휴식,50300.0,5
4,충남,세종,.,여행,체험,F,30,201901,WHITE,활동,181080.0,15
...,...,...,...,...,...,...,...,...,...,...,...,...
1691943,전남,제주,서귀포시,여행,관광쇼핑,F,30,201912,WHITE,활동,7419347.0,123
1691944,대구,제주,서귀포시,여행,숙박,M,30,201912,WHITE,휴식,6252573.0,72
1691945,충남,제주,서귀포시,여행,숙박,M,30,201912,WHITE,활동,48766328.0,350
1691946,경기,제주,서귀포시,여행,숙박,M,40,201912,RED,활동,278099747.0,1359
1691947,인천,서울,영등포구,여행,숙박,F,40,201912,WHITE,활동,8478651.0,66

In [21]:
상반기 = []
for i in range(len(df_2019)):
    if df_2019['이용년월'][i] == 201901:
        상반기.append('상반기')
    elif df_2019['이용년월'][i] == 201902:
        상반기.append('상반기')
    elif df_2019['이용년월'][i] == 201903:
        상반기.append('상반기')
    elif df_2019['이용년월'][i] == 201904:
        상반기.append('상반기')
    elif df_2019['이용년월'][i] == 201905:
        상반기.append('상반기')
    elif df_2019['이용년월'][i] == 201906:
        상반기.append('상반기')
    else:
        상반기.append('하반기')

In [22]:
df_2019['분기'] = 상반기

In [23]:
df_2019_상반기 = df_2019[df_2019['분기'] == '상반기']

In [24]:
df_2019_상반기.to_csv('./신한카드 데이터/df_2019_상반기.csv', index=False)

In [5]:
df_2020 = pd.read_csv('./신한카드 데이터/df_2020.csv')

In [6]:
df_2020.이용시간대.value_counts()

활동    377958
휴식    221547
취침     79978
Name: 이용시간대, dtype: int64